# Generated by Django 4.2 on 2023-05-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
        ('orders', '0002_alter_order_options_alter_ordertv_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.addressuser'),
        ),
    ]
