# Generated by Django 4.2 on 2023-04-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_addressuser_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressuser',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='addressuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
